server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/LootZone
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: angeloalv358@gmail.com
    password: wgta nhtm edxy emxm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
    main:
      allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        usq_sql_comments: true
jwt:
  secret: TuClaveSuperSecretaMuyLarga1234567890
  expiration: 36000000
